stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    - data/raw/wine.csv
    params:
    - prepare.test_size
    - prepare.random_state
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
    - data/processed/scaler.pkl
    - data/processed/metadata.json

  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
    params:
    - train
    outs:
    - model.pkl
